services:
  - type: web
    name: eskan-real-estate-api
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      # Supabase Configuration
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      # Frontend Configuration (Web + Mobile)
      - key: FRONTEND_URL
        value: '["https://eskan-real-estate.vercel.app", "https://eskan-real-estate-react.vercel.app", "http://localhost:3000", "exp://localhost:8081", "exp://192.168.1.7:8081"]'
      # Google Services
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      # Security Configuration
      - key: JWT_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      # API Configuration
      - key: API_BASE_URL
        value: https://eskan-real-estate-backend.onrender.com/api
      - key: WS_URL
        value: wss://eskan-real-estate-backend.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true 